coverage:
  ignore:
    - "3rdparty/**/*"
  parsers:
    gcov:
      branch_detection:
        macro: no
        loop: no
        conditional: no
        method: no
codecov:
  ci:
    - "!circleci.com"
